BREAKING CHANGE: Switched to fedora, bspwm and polybar

diff --git a/.local/bin/dtos-colorscheme b/.local/bin/dtos-colorscheme
--- a/.local/bin/dtos-colorscheme
+++ b/.local/bin/dtos-colorscheme
@@ -31,11 +31,17 @@ options=("DoomOne"
 "Mocha")
 
 choice=$(printf '%s\n' "${options[@]}" | ${DMENU} 'Choose color scheme:' "${@}")
+choicelower=$(echo "$choice" | awk '{print tolower($0)}')
 
 if [ "$choice" ]; then
     sed  -i "s/import Colors.*/import Colors.$choice/g" "$HOME"/.xmonad/README.org || echo "Cannot modify README.org"
     sed  -i "s/import Colors.*/import Colors.$choice/g" "$HOME"/.xmonad/xmonad.hs || echo "Cannot modify xmonad.hs"
+    sed  -i 's`@theme "/home/manasmengle/.local/share/rofi/themes/catppuccin-.*`@theme "/home/manasmengle/.local/share/rofi/themes/catppuccin-'$choice.rasi'"`g' /home/manasmengle/.config/rofi/config.rasi || echo "Cannot modify config.rasi"
+    sed  -i 's`include-file = colors/.*`include-file = colors/'$choice'.ini`g' /home/manasmengle/.config/polybar/config.ini || echo "Cannot modify config.ini"
+    sed  -i 's`COLORSCHEME=.*`COLORSCHEME="'$choicelower'"`g' /home/manasmengle/.config/bspwm/bspwmrc || echo "Cannor modify bspwmrc"
     xmonad --restart
+    bspc wm -r 
+    # /home/manasmengle/.config/polybar/launch.sh
 
     sed -i "s/^colors: .*/colors: \*$choice/g" "$HOME"/.config/alacritty/alacritty.yml
 
