Colorscheme: add quixotic

diff --git a/.local/bin/dtos-colorscheme b/.local/bin/dtos-colorscheme
--- a/.local/bin/dtos-colorscheme
+++ b/.local/bin/dtos-colorscheme
@@ -29,30 +29,49 @@ options=(
 "Latte"
 "Frappe"
 "Macchiato"
+"Mocha"
+"Quixotic")
+
+optionsWithAllSchemes=(
+"DoomOne"
+"Dracula"
+"GruvboxDark"
+"MonokaiPro"
+"Nord"
+"OceanicNext"
+"Palenight"
+"SolarizedDark"
+"SolarizedLight"
+"TomorrowNight"
+"Latte"
+"Frappe"
+"Macchiato"
 "Mocha")
 
 choice=$(printf '%s\n' "${options[@]}" | ${DMENU} 'Choose color scheme:' "${@}")
 choicelower=$(echo "$choice" | awk '{print tolower($0)}')
 
 if [ "$choice" ]; then
-    sed  -i "s/import Colors.*/import Colors.$choice/g" "$HOME"/.xmonad/README.org || echo "Cannot modify README.org"
-    sed  -i "s/import Colors.*/import Colors.$choice/g" "$HOME"/.xmonad/xmonad.hs || echo "Cannot modify xmonad.hs"
+    if echo "${optionsWithAllSchemes[@]}" | fgrep --word-regexp "$choice"; then # Don't have all the colorschemes for these places yet
+        sed  -i "s/import Colors.*/import Colors.$choice/g" "$HOME"/.xmonad/README.org || echo "Cannot modify README.org"
+        sed  -i "s/import Colors.*/import Colors.$choice/g" "$HOME"/.xmonad/xmonad.hs || echo "Cannot modify xmonad.hs"
+        sed  -i 's`current_theme           = catppuccin-.*`current_theme           = catppuccin-'$choicelower'`g' /home/manasmengle/.config/spicetify/config-xpui.ini || echo "Cannot modify config-xpui.ini"
+    fi
     sed  -i 's`@theme "/home/manasmengle/.local/share/rofi/themes/catppuccin-.*`@theme "/home/manasmengle/.local/share/rofi/themes/catppuccin-'$choice.rasi'"`g' /home/manasmengle/.config/rofi/config.rasi || echo "Cannot modify config.rasi"
     sed  -i 's`include-file = colors/.*`include-file = colors/'$choice'.ini`g' /home/manasmengle/.config/polybar/config.ini || echo "Cannot modify config.ini"
     sed  -i 's`COLORSCHEME=.*`COLORSCHEME="'$choicelower'"`g' /home/manasmengle/.config/bspwm/bspwmrc || echo "Cannot modify bspwmrc"
-    sed  -i 's`current_theme           = catppuccin-.*`current_theme           = catppuccin-'$choicelower'`g' /home/manasmengle/.config/spicetify/config-xpui.ini || echo "Cannot modify config-xpui.ini"
-    # xmonad --restart
+    sed -i "s/^colors: .*/colors: \*$choice/g" "$HOME"/.config/alacritty/alacritty.yml
+    
     if command -v xmonad &> /dev/null; then
       xmonad --restart
     fi
     if command -v bspc &> /dev/null; then
       bspc wm -r
     fi
-    # bspc wm -r 
     # /home/manasmengle/.config/polybar/launch.sh
     spicetify apply
 
-    sed -i "s/^colors: .*/colors: \*$choice/g" "$HOME"/.config/alacritty/alacritty.yml
+
 
 # DOOM EMACS
 
